//! Stock T3 color tokens, captured from the pinned shared theme palette.
use std::collections::HashMap;
#[derive(Debug, Clone)]
#[cfg_attr(feature = "bindings", derive(uniffi::Record))]
pub struct Theme {
    pub colors: HashMap<String, String>,
    pub header_height: f32,
    pub chat_max_width: f32,
    pub sidebar_width: f32,
    pub panel_width: f32,
    pub prompt_size: f32,
    pub code_size: f32,
    pub radius: f32,
}
#[cfg_attr(feature = "bindings", uniffi::export)]
pub fn theme(dark: bool) -> Theme {
    let colors = if dark { DARK } else { LIGHT }
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
    Theme {
        colors,
        header_height: 52.,
        chat_max_width: 736.,
        sidebar_width: 240.,
        panel_width: 540.,
        prompt_size: 14.,
        code_size: 13.,
        radius: 10.,
    }
}
const LIGHT: &[(&str, &str)] = &[
    ("canvas", "#fcfcfc"),
    ("chrome", "#fcfcfc"),
    ("toolbar", "#fcfcfc"),
    ("toolbarForeground", "#27272a"),
    ("toolbarBorder", "#e4e4e7"),
    ("toolbarControl", "#ffffff"),
    ("toolbarControlForeground", "#27272a"),
    ("toolbarControlHover", "#f4f4f5"),
    ("surface", "#ffffff"),
    ("surfaceRaised", "#fcfcfc"),
    ("surfaceOverlay", "#ffffff"),
    ("text", "#27272a"),
    ("textMuted", "#71717b"),
    ("border", "#e4e4e7"),
    ("input", "#d4d4d8"),
    ("focus", "#1b4ed8"),
    ("accent", "#1b4ed8"),
    ("accentForeground", "#ffffff"),
    ("secondary", "#fafafa"),
    ("secondaryForeground", "#27272a"),
    ("muted", "#fafafa"),
    ("mutedForeground", "#71717b"),
    ("placeholder", "#71717b"),
    ("secondaryLabel", "#71717b"),
    ("iconMuted", "#71717b"),
    ("error", "#fb2c36"),
    ("errorForeground", "#c10007"),
    ("errorSurface", "#fcebec"),
    ("warning", "#fe9a00"),
    ("warningForeground", "#bb4d00"),
    ("warningSurface", "#fcf4e8"),
    ("update", "#1b4ed8"),
    ("updateForeground", "#1b4ed8"),
    ("updateSurface", "#e0e6f7"),
    ("accentSurface", "#f4f4f5"),
    ("accentSurfaceForeground", "#18181b"),
    ("messageSurface", "#f4f4f5"),
    ("messageForeground", "#27272a"),
    ("messageAction", "#1b4ed8"),
    ("messageActionForeground", "#ffffff"),
    ("messageActionHover", "#3160db"),
    ("codeBackground", "#ffffff"),
    ("codeForeground", "#27272a"),
    ("sidebar", "#fafafa"),
    ("sidebarForeground", "#27272a"),
    ("sidebarMutedForeground", "#71717b"),
    ("sidebarControlSurface", "#f4f4f5"),
    ("sidebarRowHover", "#fcfcfc"),
    ("sidebarRowActive", "#ffffff"),
    ("sidebarRowSelected", "#ffffff"),
    ("sidebarBorder", "#e4e4e7"),
    ("terminalBackground", "#fcfcfc"),
    ("terminalForeground", "#27272a"),
    ("terminalCursor", "#26384e"),
    ("terminalSelection", "#d0d6dd"),
    ("terminalScrollbar", "#d6d6d6"),
    ("terminalScrollbarHover", "#bdbdbd"),
];
const DARK: &[(&str, &str)] = &[
    ("canvas", "#0a0a0a"),
    ("chrome", "#0a0a0a"),
    ("toolbar", "#0a0a0a"),
    ("toolbarForeground", "#f5f5f5"),
    ("toolbarBorder", "#191919"),
    ("toolbarControl", "#111111"),
    ("toolbarControlForeground", "#f5f5f5"),
    ("toolbarControlHover", "#141414"),
    ("surface", "#111111"),
    ("surfaceRaised", "#111111"),
    ("surfaceOverlay", "#111111"),
    ("text", "#f5f5f5"),
    ("textMuted", "#818181"),
    ("border", "#191919"),
    ("input", "#1e1e1e"),
    ("focus", "#346bf1"),
    ("accent", "#346bf1"),
    ("accentForeground", "#ffffff"),
    ("secondary", "#111111"),
    ("secondaryForeground", "#f5f5f5"),
    ("muted", "#111111"),
    ("mutedForeground", "#818181"),
    ("placeholder", "#818181"),
    ("secondaryLabel", "#818181"),
    ("iconMuted", "#818181"),
    ("error", "#fb414a"),
    ("errorForeground", "#ff6467"),
    ("errorSurface", "#301214"),
    ("warning", "#fe9a00"),
    ("warningForeground", "#ffb900"),
    ("warningSurface", "#312108"),
    ("update", "#346bf1"),
    ("updateForeground", "#51a2ff"),
    ("updateSurface", "#121b34"),
    ("accentSurface", "#141414"),
    ("accentSurfaceForeground", "#f5f5f5"),
    ("messageSurface", "#141414"),
    ("messageForeground", "#f5f5f5"),
    ("messageAction", "#346bf1"),
    ("messageActionForeground", "#ffffff"),
    ("messageActionHover", "#3061d9"),
    ("codeBackground", "#111111"),
    ("codeForeground", "#f5f5f5"),
    ("sidebar", "#000000"),
    ("sidebarForeground", "#f1f3f7"),
    ("sidebarMutedForeground", "#a3a3a3"),
    ("sidebarControlSurface", "#0a0a0a"),
    ("sidebarRowHover", "#131313"),
    ("sidebarRowActive", "#1a1b1b"),
    ("sidebarRowSelected", "#111111"),
    ("sidebarBorder", "#141414"),
    ("terminalBackground", "#0a0a0a"),
    ("terminalForeground", "#f5f5f5"),
    ("terminalCursor", "#b4cbff"),
    ("terminalSelection", "#343a47"),
    ("terminalScrollbar", "#222222"),
    ("terminalScrollbarHover", "#363636"),
];
