//! Stock color tokens, captured from the pinned shared theme palette, with the
//! mobile palette (`mobile*`, `#rrggbbaa` where it is translucent) and the
//! status hues (`status*`) both mobile apps read.
use std::collections::HashMap;
#[derive(Debug, Clone)]
#[cfg_attr(feature = "bindings", derive(uniffi::Record))]
pub struct Theme {
    pub colors: HashMap<String, String>,
    pub header_height: f32,
    pub chat_max_width: f32,
    pub sidebar_width: f32,
    pub panel_width: f32,
    pub prompt_size: f32,
    pub code_size: f32,
    pub radius: f32,
}
#[cfg_attr(feature = "bindings", uniffi::export)]
pub fn theme(dark: bool) -> Theme {
    let colors = if dark { DARK } else { LIGHT }
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect();
    Theme {
        colors,
        header_height: 52.,
        chat_max_width: 736.,
        sidebar_width: 256.,
        panel_width: 540.,
        prompt_size: 14.,
        code_size: 13.,
        radius: 10.,
    }
}
const LIGHT: &[(&str, &str)] = &[
    ("mobileScreen", "#fcfcfc"),
    ("mobileSheet", "#fcfcfc"),
    ("mobileCard", "#ffffff"),
    ("mobileCardAlt", "#fcfcfc"),
    ("mobileRowHover", "#f4f4f5"),
    ("mobileComposerPanel", "#fcfcfc"),
    ("mobileComposerSurface", "#f4f4f5ef"),
    ("mobileComposerBorder", "#e4e4e7cc"),
    ("mobileForeground", "#27272a"),
    ("mobileForegroundSecondary", "#6f6f79"),
    ("mobileForegroundMuted", "#6f6f79"),
    ("mobileForegroundTertiary", "#71717b"),
    ("mobileBorder", "#e4e4e7"),
    ("mobileBorderSubtle", "#e4e4e7b2"),
    ("mobileSeparator", "#e4e4e78c"),
    ("mobileSubtle", "#fafafa"),
    ("mobileSubtleStrong", "#fafafa"),
    ("mobilePrimary", "#1b4ed8"),
    ("mobilePrimaryForeground", "#ffffff"),
    ("mobileSecondary", "#fafafa"),
    ("mobileSecondaryForeground", "#27272a"),
    ("mobileWarning", "#fcf4e8"),
    ("mobileWarningBorder", "#fe9a0051"),
    ("mobileWarningForeground", "#bb4d00"),
    ("mobileDanger", "#fcebec"),
    ("mobileDangerBorder", "#fb2c3651"),
    ("mobileDangerForeground", "#c10007"),
    ("mobileUpdate", "#e0e6f7"),
    ("mobileUpdateForeground", "#1b4ed8"),
    ("mobileInput", "#ffffff"),
    ("mobileInputBorder", "#d4d4d8"),
    ("mobilePlaceholder", "#6f6f79"),
    ("mobileIcon", "#27272a"),
    ("mobileIconMuted", "#71717b"),
    ("mobileHeader", "#f4f4f5"),
    ("mobileHeaderForeground", "#27272a"),
    ("mobileMarkdownCode", "#ffffff"),
    ("mobileMarkdownBlockquoteBorder", "#e4e4e7"),
    ("mobileMarkdownRule", "#e4e4e7"),
    ("mobileUserBubbleForeground", "#27272a"),
    ("mobileBackdrop", "#00000038"),
    ("mobileDrawer", "#fafafa"),
    ("mobileChevron", "#71717b6b"),
    ("statusSky", "#0284c7"),
    ("statusIndigo", "#4f46e5"),
    ("statusEmerald", "#047857"),
    ("statusEmeraldIcon", "#059669"),
    ("statusRose", "#e11d48"),
    ("statusRoseText", "#be123c"),
    ("statusAmber", "#b45309"),
    ("statusViolet", "#7c3aed"),
    ("statusTeal", "#0d9488"),
    ("mobileUserBubble", "#efeff1"),
    ("mobileComposer", "#f4f4f5"),
    ("mobileGroupedCard", "#f4f4f5"),
    ("mobileSelected", "#ffffff"),
    ("mobilePrimaryText", "#1b4ed8"),
    ("mobileMarkdownLink", "#1b4ed8"),
    ("canvas", "#fcfcfc"),
    ("chrome", "#fcfcfc"),
    ("toolbar", "#fcfcfc"),
    ("toolbarForeground", "#27272a"),
    ("toolbarBorder", "#e4e4e7"),
    ("toolbarControl", "#ffffff"),
    ("toolbarControlForeground", "#27272a"),
    ("toolbarControlHover", "#f4f4f5"),
    ("surface", "#ffffff"),
    ("surfaceRaised", "#fcfcfc"),
    ("surfaceOverlay", "#ffffff"),
    ("text", "#27272a"),
    ("textMuted", "#71717b"),
    ("border", "#e4e4e7"),
    ("input", "#d4d4d8"),
    ("focus", "#1b4ed8"),
    ("accent", "#1b4ed8"),
    ("accentForeground", "#ffffff"),
    ("secondary", "#fafafa"),
    ("secondaryForeground", "#27272a"),
    ("muted", "#fafafa"),
    ("mutedForeground", "#71717b"),
    ("placeholder", "#71717b"),
    ("secondaryLabel", "#71717b"),
    ("iconMuted", "#71717b"),
    ("error", "#fb2c36"),
    ("errorForeground", "#c10007"),
    ("errorSurface", "#fcebec"),
    ("warning", "#fe9a00"),
    ("warningForeground", "#bb4d00"),
    ("warningSurface", "#fcf4e8"),
    ("successForeground", "#007a55"),
    ("inputForeground", "#4f46e5"),
    ("update", "#1b4ed8"),
    ("updateForeground", "#1b4ed8"),
    ("updateSurface", "#e0e6f7"),
    ("accentSurface", "#f4f4f5"),
    ("accentSurfaceForeground", "#18181b"),
    ("messageSurface", "#f4f4f5"),
    ("messageForeground", "#27272a"),
    ("messageAction", "#1b4ed8"),
    ("messageActionForeground", "#ffffff"),
    ("messageActionHover", "#3160db"),
    ("codeBackground", "#ffffff"),
    ("codeForeground", "#27272a"),
    ("sidebar", "#fafafa"),
    ("sidebarForeground", "#27272a"),
    ("sidebarMutedForeground", "#71717b"),
    ("sidebarControlSurface", "#f4f4f5"),
    ("sidebarRowHover", "#fcfcfc"),
    ("sidebarRowActive", "#ffffff"),
    ("sidebarRowSelected", "#ffffff"),
    ("sidebarBorder", "#e4e4e7"),
    ("terminalBackground", "#fcfcfc"),
    ("terminalForeground", "#27272a"),
    ("terminalCursor", "#26384e"),
    ("terminalSelection", "#d0d6dd"),
    ("terminalScrollbar", "#d6d6d6"),
    ("terminalScrollbarHover", "#bdbdbd"),
];
const DARK: &[(&str, &str)] = &[
    ("mobileScreen", "#0a0a0a"),
    ("mobileSheet", "#0a0a0a"),
    ("mobileCard", "#111111"),
    ("mobileCardAlt", "#111111"),
    ("mobileRowHover", "#141414"),
    ("mobileComposerPanel", "#0a0a0a"),
    ("mobileComposerSurface", "#1a1b1be5"),
    ("mobileComposerBorder", "#191919cc"),
    ("mobileForeground", "#f5f5f5"),
    ("mobileForegroundSecondary", "#838383"),
    ("mobileForegroundMuted", "#838383"),
    ("mobileForegroundTertiary", "#818181"),
    ("mobileBorder", "#191919"),
    ("mobileBorderSubtle", "#191919b2"),
    ("mobileSeparator", "#1919198c"),
    ("mobileSubtle", "#111111"),
    ("mobileSubtleStrong", "#111111"),
    ("mobilePrimary", "#346bf1"),
    ("mobilePrimaryForeground", "#ffffff"),
    ("mobileSecondary", "#111111"),
    ("mobileSecondaryForeground", "#f5f5f5"),
    ("mobileWarning", "#312108"),
    ("mobileWarningBorder", "#fe9a0051"),
    ("mobileWarningForeground", "#ffb900"),
    ("mobileDanger", "#301214"),
    ("mobileDangerBorder", "#fb414a51"),
    ("mobileDangerForeground", "#ff6467"),
    ("mobileUpdate", "#121b34"),
    ("mobileUpdateForeground", "#51a2ff"),
    ("mobileInput", "#111111"),
    ("mobileInputBorder", "#1e1e1e"),
    ("mobilePlaceholder", "#838383"),
    ("mobileIcon", "#f5f5f5"),
    ("mobileIconMuted", "#818181"),
    ("mobileHeader", "#141414"),
    ("mobileHeaderForeground", "#f1f3f7"),
    ("mobileMarkdownCode", "#111111"),
    ("mobileMarkdownBlockquoteBorder", "#191919"),
    ("mobileMarkdownRule", "#191919"),
    ("mobileUserBubbleForeground", "#f5f5f5"),
    ("mobileBackdrop", "#0000007a"),
    ("mobileDrawer", "#000000"),
    ("mobileChevron", "#8181816b"),
    ("statusSky", "#38bdf8"),
    ("statusIndigo", "#a5b4fc"),
    ("statusEmerald", "#6ee7b7"),
    ("statusEmeraldIcon", "#34d399"),
    ("statusRose", "#fb7185"),
    ("statusRoseText", "#fda4af"),
    ("statusAmber", "#fcd34d"),
    ("statusViolet", "#a78bfa"),
    ("statusTeal", "#5eead4e5"),
    ("mobileUserBubble", "#161616"),
    ("mobileComposer", "#1a1b1b"),
    ("mobileGroupedCard", "#1a1b1b"),
    ("mobileSelected", "#1a1b1b"),
    ("mobilePrimaryText", "#4b7cf3"),
    ("mobileMarkdownLink", "#3b70f1"),
    ("canvas", "#0a0a0a"),
    ("chrome", "#0a0a0a"),
    ("toolbar", "#0a0a0a"),
    ("toolbarForeground", "#f5f5f5"),
    ("toolbarBorder", "#191919"),
    ("toolbarControl", "#111111"),
    ("toolbarControlForeground", "#f5f5f5"),
    ("toolbarControlHover", "#141414"),
    ("surface", "#111111"),
    ("surfaceRaised", "#111111"),
    ("surfaceOverlay", "#111111"),
    ("text", "#f5f5f5"),
    ("textMuted", "#818181"),
    ("border", "#191919"),
    ("input", "#1e1e1e"),
    ("focus", "#346bf1"),
    ("accent", "#346bf1"),
    ("accentForeground", "#ffffff"),
    ("secondary", "#111111"),
    ("secondaryForeground", "#f5f5f5"),
    ("muted", "#111111"),
    ("mutedForeground", "#818181"),
    ("placeholder", "#818181"),
    ("secondaryLabel", "#818181"),
    ("iconMuted", "#818181"),
    ("error", "#fb414a"),
    ("errorForeground", "#ff6467"),
    ("errorSurface", "#301214"),
    ("warning", "#fe9a00"),
    ("warningForeground", "#ffb900"),
    ("warningSurface", "#312108"),
    ("successForeground", "#00d492"),
    ("inputForeground", "#a5b4fc"),
    ("update", "#346bf1"),
    ("updateForeground", "#51a2ff"),
    ("updateSurface", "#121b34"),
    ("accentSurface", "#141414"),
    ("accentSurfaceForeground", "#f5f5f5"),
    ("messageSurface", "#141414"),
    ("messageForeground", "#f5f5f5"),
    ("messageAction", "#346bf1"),
    ("messageActionForeground", "#ffffff"),
    ("messageActionHover", "#3061d9"),
    ("codeBackground", "#111111"),
    ("codeForeground", "#f5f5f5"),
    ("sidebar", "#000000"),
    ("sidebarForeground", "#f1f3f7"),
    ("sidebarMutedForeground", "#a3a3a3"),
    ("sidebarControlSurface", "#0a0a0a"),
    ("sidebarRowHover", "#131313"),
    ("sidebarRowActive", "#1a1b1b"),
    ("sidebarRowSelected", "#111111"),
    ("sidebarBorder", "#141414"),
    ("terminalBackground", "#0a0a0a"),
    ("terminalForeground", "#f5f5f5"),
    ("terminalCursor", "#b4cbff"),
    ("terminalSelection", "#343a47"),
    ("terminalScrollbar", "#222222"),
    ("terminalScrollbarHover", "#363636"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_appearances_name_the_same_tokens_in_hex() {
        let names = |tokens: &[(&'static str, &'static str)]| {
            let mut names: Vec<&'static str> = tokens.iter().map(|(name, _)| *name).collect();
            names.sort_unstable();
            names
        };
        assert_eq!(names(LIGHT), names(DARK));
        for (_, value) in LIGHT.iter().chain(DARK) {
            assert!(
                matches!(value.len(), 7 | 9)
                    && value.starts_with('#')
                    && value[1..].chars().all(|c| c.is_ascii_hexdigit()),
                "{value}"
            );
        }
        assert_eq!(theme(true).colors["statusSky"], "#38bdf8");
    }
}
