import XCTest

extension BexLaunchUITests {
    func testSimulatorSelectsModelScopeAndShowsUsageBeforeManagingAccounts() throws {
        let app = try connectedSimulatorApp()
        app.buttons["tasks.menu"].tap(); app.buttons["tasks.settings"].tap()
        app.buttons["settings.models"].tap()
        let choice = app.buttons["model.choice.fixture-model"]
        XCTAssertTrue(choice.waitForExistence(timeout: 15)); choice.tap()
        app.buttons["model.sheet.effort"].tap(); app.buttons["medium"].tap()
        app.buttons["settings.scope.environment"].tap()
        app.buttons["settings.scope.environment.current"].tap()
        app.buttons["model.sheet.effort"].tap(); app.buttons["high"].tap()
        app.buttons["model.defaults.speed"].tap(); app.buttons["高速"].tap()
        app.buttons["settings.scope.projects"].tap()
        app.buttons["settings.scope.projects.simulator-project"].tap()
        XCTAssertEqual(app.buttons["model.sheet.effort"].value as? String, "high")
        app.buttons["model.sheet.effort"].tap(); app.buttons["medium"].tap()
        XCTAssertTrue(app.buttons["model.defaults.inherit"].exists)
        captureScreen(app, named: "Project model defaults with environment inheritance")
        app.buttons["model.defaults.inherit"].tap()
        XCTAssertEqual(app.buttons["model.sheet.effort"].value as? String, "high")
        XCTAssertFalse(app.buttons["model.defaults.inherit"].exists)
        app.buttons["model.close"].tap()
        app.buttons["tasks.new.project.simulator-project"].tap()
        XCTAssertEqual(app.buttons["model.effort"].value as? String, "high")
        XCTAssertEqual(app.buttons["model.fast"].value as? String, "オン")
        app.buttons["model.settings"].tap()
        XCTAssertTrue(app.buttons["settings.scope.projects"].label.contains("この会話"))
        XCTAssertTrue(app.staticTexts["残り 86%"].waitForExistence(timeout: 15))
        XCTAssertTrue(app.staticTexts["残り 86%"].isHittable)
        XCTAssertTrue(app.staticTexts["残り 72%"].isHittable)
        captureScreen(app, named: "Conversation model settings with quota visible immediately")
        app.buttons["settings.scope.projects"].tap()
        app.buttons["settings.scope.projects.simulator-project"].tap()
        app.buttons["model.sheet.effort"].tap(); app.buttons["medium"].tap()
        app.buttons["settings.scope.projects"].tap()
        app.buttons["settings.scope.projects.conversation"].tap()
        XCTAssertEqual(app.buttons["model.sheet.effort"].value as? String, "high")
        app.terminate(); app.launch()
        XCTAssertTrue(app.buttons["tasks.menu"].waitForExistence(timeout: 20))
        app.buttons["tasks.menu"].tap(); app.buttons["tasks.settings"].tap()
        app.buttons["settings.models"].tap()
        app.buttons["settings.scope.projects"].tap()
        app.buttons["settings.scope.projects.simulator-project"].tap()
        XCTAssertEqual(app.buttons["model.sheet.effort"].value as? String, "medium")
    }
}
