[package]
name = "mobile-client"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
jni = ["dep:jni"]

[dependencies]
russh.workspace = true
relay-transport = { path = "../relay-transport" }
thiserror.workspace = true
tokio-util.workspace = true
agent-core = { path = "../agent-core" }
conversation-presentation = { path = "../conversation-presentation" }
jni = { version = "0.21.1", optional = true }
base64.workspace = true
host-protocol = { path = "../host-protocol" }
ring.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
tokio = { workspace = true, features = ["net", "fs"] }
zeroize.workspace = true
