// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "BexNativeState",
    products: [.library(name: "BexNativeState", targets: ["BexNativeState"])],
    targets: [
        .target(
            name: "BexNativeState",
            path: "Bex",
            exclude: [
                "AccountViews.swift",
                "AgentPushCenter+ActivityLifecycle.swift",
                "AgentPushCenter+Notifications.swift",
                "AgentPushCenter+Routing.swift",
                "AgentPushCenter.swift",
                "AgentsSheet.swift",
                "AppPresentationData.swift",
                "AppViewActions.swift",
                "AppViewModel.swift",
                "AppViewModelActions.swift",
                "AppViewModelConnection.swift",
                "AppViewModelEnvironment.swift",
                "AppViewModelObservation.swift",
                "AppViewModelPush.swift",
                "AppViewModelRouting.swift",
                "ArchivedScreen.swift",
                "Assets.xcassets",
                "BexIOSApp.swift",
                "BranchPicker.swift",
                "Composer.swift",
                "ComposerAttachments.swift",
                "ComposerMenu.swift",
                "ConversationMarkdown.swift",
                "ConversationMedia.swift",
                "DeviceLiveFramePanel.swift",
                "DeviceRecordingViews.swift",
                "DeviceScreen.swift",
                "DeviceScreenContent.swift",
                "DeviceScreenSupport.swift",
                "DeviceSessionControls.swift",
                "DeviceVideoDecoder.swift",
                "DeviceVideoDecoderSupport.swift",
                "DictationRecorder.swift",
                "FeedDividers.swift",
                "FeedRows.swift",
                "GitControls.swift",
                "GitPullRequestSection.swift",
                "GitSheetSections.swift",
                "GitSheets.swift",
                "Info.plist",
                "NewTaskFlow.swift",
                "PairingScreens.swift",
                "PlatformNotifications.swift",
                "PlatformPersistence.swift",
                "PlatformSharing.swift",
                "PlatformUI.swift",
                "PrivacyInfo.xcprivacy",
                "QRCodeCaptureViewController.swift",
                "QueueSheet.swift",
                "RemoteAgent.entitlements",
                "RemoteAgentCompletion.caf",
                "RemoteAgentInput.caf",
                "RemoteFolderPicker.swift",
                "RequestCards.swift",
                "ReviewScreen.swift",
                "ScheduledTaskBranchPicker.swift",
                "ScheduledTaskEditor.swift",
                "ScheduledTasksScreen.swift",
                "SettingsAccounts.swift",
                "SettingsAuxiliaryPages.swift",
                "SettingsControls.swift",
                "SettingsScreen.swift",
                "SetupCard.swift",
                "SnoozeSheet.swift",
                "SwiftUIRoot.swift",
                "TerminalScreen.swift",
                "TerminalTools.swift",
                "Theme.swift",
                "ThreadArrangementSheet.swift",
                "ThreadListHeader.swift",
                "ThreadListRows.swift",
                "ThreadListScreen.swift",
                "ThreadPresentation.swift",
                "ThreadScreen.swift",
                "ThreadSettingsSheet.swift",
                "ThreadSwipeActions.swift",
                "UsageScreen.swift",
                "UsageWidgetPublisher.swift",
                "WorkLogRows.swift",
                "WorkingControl.swift",
                "WorkspaceFileEditor.swift",
                "WorkspaceScreen.swift",
                "WorkspaceViews.swift",
                "WorktreeSettings.swift"
            ],
            sources: ["DraftRevision.swift", "ImageSizing.swift"]
        ),
        .testTarget(name: "BexNativeStateTests", dependencies: ["BexNativeState"], path: "UnitTests")
    ]
)
