#!/usr/bin/env bash
# Share fixed tooling and dependency bytes; keep mutable Cargo state local.
set -euo pipefail
cd "$(dirname "$0")/.."
bex_root=$PWD
bex_build_root=$(git config --path --get bex.buildRoot || true)
if [[ -n $bex_build_root ]]; then
    # Keep conventional target paths for Cargo, Xcode and generated bindings.
    # Never create the root: an unplugged build volume must fail visibly.
    if [[ $bex_build_root != /* || ! -d $bex_build_root ]]; then
        printf 'Build storage is unavailable: %s\n' "$bex_build_root" >&2
        exit 1
    fi
    # Keep the shared compiler cache on the build volume for CoW restores.
    export KACHE_CACHE_DIR="${KACHE_CACHE_DIR:-$bex_build_root/.kache}"
    if [[ ! -e $bex_root/target && ! -L $bex_root/target ]]; then
        bex_build_key=$(printf '%s\n' "$bex_root" | git hash-object --stdin)
        mkdir -p "$bex_build_root/$bex_build_key"
        # Do not follow a directory link created by a concurrent invocation.
        ln -sn "$bex_build_root/$bex_build_key" "$bex_root/target" ||
            [[ -L $bex_root/target && $(readlink "$bex_root/target") == "$bex_build_root/$bex_build_key" ]]
    fi
fi
# A dangling target link means the configured build volume is unavailable.
# Fail before Cargo or Nix can create state through a broken path. When no
# build root is configured, keep the conventional target directory usable.
if [[ -L $bex_root/target && ! -e $bex_root/target ]]; then
    printf 'Build target is unavailable: %s\n' "$bex_root/target" >&2
    exit 1
fi
if [[ ! -e $bex_root/target ]]; then
    mkdir -p "$bex_root/target"
fi
if [[ ! -d $bex_root/target ]]; then
    printf 'Build target is not a directory: %s\n' "$bex_root/target" >&2
    exit 1
fi
if ! bex_target_dir=$(cd "$bex_root/target" && pwd -P); then
    printf 'Build target cannot be canonicalized: %s\n' "$bex_root/target" >&2
    exit 1
fi
bex_seed_cargo=${CARGO_HOME:-$HOME/.cargo}
export XDG_CACHE_HOME="$bex_target_dir/tool-cache"
bex_env_key=$({ git hash-object flake.nix flake.lock tools/kache/package.nix; uname -sm; } | git hash-object --stdin)
bex_env_dir="$(git rev-parse --git-common-dir)/bex-dev-env/$bex_env_key"
mkdir -p "$bex_env_dir"
if [[ ! -f $bex_env_dir/env.sh ]]; then
    bex_pending_env=$(mktemp -d "$bex_env_dir/bootstrap.XXXXXX")
    trap 'rm -rf "$bex_pending_env"' EXIT
    nix --option eval-cache false print-dev-env . --no-update-lock-file \
        --profile "$bex_pending_env/profile" > "$bex_pending_env/env.sh"
    # Publish once, without a shared reader lock. Keep the winning GC root.
    if ! ln "$bex_pending_env/env.sh" "$bex_env_dir/env.sh" 2>/dev/null; then
        [[ -f $bex_env_dir/env.sh ]]
        rm -rf "$bex_pending_env"
    fi
    trap - EXIT
fi
# Nix emits Bash 4+ functions; macOS /bin/bash is still Bash 3. Use the
# shell recorded in the pinned environment before evaluating that code.
# Read only Nix's quoted store path, without evaluating the environment.
bex_shell=$(sed -n "s|^BASH='\(/nix/store/[^']*/bin/bash\)'$|\1|p" "$bex_env_dir/env.sh")
if [[ ! -x $bex_shell ]]; then
    printf 'Pinned Bash is unavailable in %s\n' "$bex_env_dir/env.sh" >&2
    exit 1
fi
if [[ $BASH != "$bex_shell" ]]; then
    exec "$bex_shell" "$bex_root/scripts/dev-env.sh" "$@"
fi
bex_original_tmpdir=${TMPDIR:-/tmp}
bex_original_build_top=${NIX_BUILD_TOP-}
# Generated by nix print-dev-env from the current pinned flake.
# shellcheck disable=SC1091
source "$bex_env_dir/env.sh"
# print-dev-env creates a fresh shell directory; these commands need only the
# environment. Restore the caller's temporary directory and remove the empty one.
rmdir "$NIX_BUILD_TOP"
export TMPDIR="$bex_original_tmpdir" TMP="$bex_original_tmpdir"
export TEMP="$bex_original_tmpdir" TEMPDIR="$bex_original_tmpdir"
if [[ -n $bex_original_build_top ]]; then
    export NIX_BUILD_TOP="$bex_original_build_top"
else
    unset NIX_BUILD_TOP
fi
if ! bex_target_dir=$(realpath "$bex_root/target"); then
    printf 'Build target cannot be canonicalized: %s\n' "$bex_root/target" >&2
    exit 1
fi
if [[ $bex_target_dir != /* || ! -d $bex_target_dir ]]; then
    printf 'Canonical build target is unavailable: %s\n' "$bex_target_dir" >&2
    exit 1
fi
export XDG_CACHE_HOME="$bex_target_dir/tool-cache"
export CARGO_TARGET_DIR="$bex_target_dir"
export CARGO_HOME="$bex_target_dir/cargo-home"
bex_seed_key=$(git hash-object Cargo.lock tools/agent-peer/Cargo.lock | git hash-object --stdin)
if [[ ! -f $CARGO_HOME/.seeded || $(< "$CARGO_HOME/.seeded") != "$bex_seed_key" ]]; then
    mkdir -p "$CARGO_HOME/registry" "$CARGO_HOME/git/db" "$CARGO_HOME/git/checkouts"
    bex_copy_cache() {
        if [[ $(uname -s) == Darwin ]]; then
            /bin/cp -cpR "$@" || /bin/cp -pR "$@"
        else
            cp --reflink=auto -pR "$@"
        fi
    }
    # Clone only locked sources and archives. APFS/reflinks share their bytes
    # without sharing Cargo's locks, index updates or automatic cache deletion.
    bex_packages=()
    while IFS= read -r bex_package; do bex_packages+=("$bex_package"); done < <(
        awk '/^name = / { name = $3; gsub(/"/, "", name) }
             /^version = / { version = $3; gsub(/"/, "", version) }
             /^source = "registry\+https:\/\/github.com\/rust-lang\/crates.io-index"/ { print name "-" version }' \
            Cargo.lock tools/agent-peer/Cargo.lock | sort -u
    )
    if [[ $bex_seed_cargo != "$CARGO_HOME" ]]; then
        for bex_index in "$bex_seed_cargo/registry/index"/index.crates.io-*; do
            [[ -d $bex_index ]] || continue
            bex_registry=${bex_index##*/}
            mkdir -p "$CARGO_HOME/registry/index"
            if [[ ! -d $CARGO_HOME/registry/index/$bex_registry ]]; then
                bex_copy_cache "$bex_index" "$CARGO_HOME/registry/index/"
            fi
            for bex_kind in src cache; do
                bex_suffix=
                [[ $bex_kind == cache ]] && bex_suffix=.crate
                bex_destination="$CARGO_HOME/registry/$bex_kind/$bex_registry"
                mkdir -p "$bex_destination"
                bex_sources=()
                for bex_package in "${bex_packages[@]}"; do
                    bex_cached="$bex_seed_cargo/registry/$bex_kind/$bex_registry/$bex_package$bex_suffix"
                    if [[ -e $bex_cached && ! -e $bex_destination/$bex_package$bex_suffix ]]; then
                        bex_sources+=("$bex_cached")
                    fi
                done
                if (( ${#bex_sources[@]} )); then
                    bex_copy_cache "${bex_sources[@]}" "$bex_destination/"
                fi
            done
        done
        while read -r bex_repo bex_revision; do
            for bex_cached in "$bex_seed_cargo/git/db/$bex_repo"-*; do
                if [[ -d $bex_cached && ! -e $CARGO_HOME/git/db/${bex_cached##*/} ]]; then
                    bex_copy_cache "$bex_cached" "$CARGO_HOME/git/db/"
                fi
            done
            for bex_checkout in "$bex_seed_cargo/git/checkouts/$bex_repo"-*; do
                bex_cached="$bex_checkout/$bex_revision"
                bex_destination="$CARGO_HOME/git/checkouts/${bex_checkout##*/}"
                if [[ -d $bex_cached && ! -e $bex_destination/$bex_revision ]]; then
                    mkdir -p "$bex_destination"
                    bex_copy_cache "$bex_cached" "$bex_destination/"
                fi
            done
        done < <(awk '/^source = "git\+/ {
            source = $3; gsub(/"/, "", source); split(source, parts, "#")
            revision = substr(parts[2], 1, 7)
            sub(/[?#].*/, "", source); sub(/.*\//, "", source); sub(/\.git$/, "", source)
            print source, revision
        }' Cargo.lock tools/agent-peer/Cargo.lock | sort -u)
    fi
    printf '%s\n' "$bex_seed_key" > "$CARGO_HOME/.seeded"
fi
exec "$@"
