package dev.remoteagent.mobile

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.AtomicFile
import java.io.ByteArrayOutputStream
import java.io.File
import java.security.MessageDigest
import java.security.KeyStore
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Stores the PKCS#8 key generated by the native mobile-client implementation.
 *
 * Android Keystore does not hold this Ed25519 key directly on all supported API levels, so it
 * protects the opaque PKCS#8 value with a non-exportable AES-GCM key. The returned bytes are
 * intended only for an immediate native-client call and must never be logged or placed in a
 * HostProfile/cache record.
 */
class AndroidDeviceIdentityStore(context: Context, hostIdentity: String) {
    private val identifier = stableIdentifier(hostIdentity)
    private val keyStoreAlias = "remote-agent.identity.$identifier"
    private val encryptedFile = AtomicFile(File(context.filesDir, "device-identity-$identifier.v1"))

    fun deviceIdentityReference(): String = keyStoreAlias

    @Synchronized
    fun loadOrCreate(createPkcs8: () -> ByteArray): ByteArray {
        if (encryptedFile.baseFile.exists()) return decrypt(readFile())

        val pkcs8 = createPkcs8()
        require(pkcs8.isNotEmpty() && pkcs8.size <= MaximumPkcs8Bytes) { "Invalid device identity" }
        try {
            writeFile(encrypt(pkcs8))
            return pkcs8.copyOf()
        } finally {
            pkcs8.fill(0)
        }
    }

    @Synchronized
    fun load(): ByteArray? = if (encryptedFile.baseFile.exists()) decrypt(readFile()) else null

    private fun encrypt(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AesGcmTransformation)
        cipher.init(Cipher.ENCRYPT_MODE, encryptionKey())
        cipher.updateAAD(AssociatedData)
        val ciphertext = cipher.doFinal(plaintext)
        return ByteArrayOutputStream(2 + cipher.iv.size + ciphertext.size).use { bytes ->
            bytes.write(FormatVersion)
            bytes.write(cipher.iv.size)
            bytes.write(cipher.iv)
            bytes.write(ciphertext)
            bytes.toByteArray()
        }
    }

    private fun decrypt(encoded: ByteArray): ByteArray {
        require(encoded.size > 2 && encoded[0].toInt() == FormatVersion) { "Unreadable device identity" }
        val ivSize = encoded[1].toInt() and 0xff
        require(ivSize in 12..16 && encoded.size > 2 + ivSize) { "Unreadable device identity" }
        val cipher = Cipher.getInstance(AesGcmTransformation)
        cipher.init(Cipher.DECRYPT_MODE, encryptionKey(), GCMParameterSpec(128, encoded, 2, ivSize))
        cipher.updateAAD(AssociatedData)
        return cipher.doFinal(encoded, 2 + ivSize, encoded.size - 2 - ivSize).also {
            require(it.isNotEmpty() && it.size <= MaximumPkcs8Bytes) { "Unreadable device identity" }
        }
    }

    private fun encryptionKey(): SecretKey {
        val keyStore = KeyStore.getInstance(AndroidKeyStore).apply { load(null) }
        return (keyStore.getEntry(keyStoreAlias, null) as? KeyStore.SecretKeyEntry)?.secretKey
            ?: KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, AndroidKeyStore).apply {
                init(
                    KeyGenParameterSpec.Builder(keyStoreAlias, KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT)
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        .setRandomizedEncryptionRequired(true)
                        .build(),
                )
            }.generateKey()
    }

    private fun readFile(): ByteArray = encryptedFile.openRead().use { input ->
        input.readBytes().also { require(it.size <= MaximumEncryptedBytes) { "Unreadable device identity" } }
    }

    private fun writeFile(bytes: ByteArray) {
        val output = encryptedFile.startWrite()
        try {
            output.write(bytes)
            output.fd.sync()
            encryptedFile.finishWrite(output)
        } catch (error: Throwable) {
            encryptedFile.failWrite(output)
            throw error
        }
    }

    private companion object {
        const val AndroidKeyStore = "AndroidKeyStore"
        const val AesGcmTransformation = "AES/GCM/NoPadding"
        const val FormatVersion = 1
        const val MaximumPkcs8Bytes = 16 * 1024
        const val MaximumEncryptedBytes = MaximumPkcs8Bytes + 64
        val AssociatedData = "dev.remoteagent.mobile/device-identity/v1".encodeToByteArray()
        fun stableIdentifier(hostIdentity: String): String {
            require(hostIdentity.isNotBlank()) { "Missing host identity" }
            val digest = MessageDigest.getInstance("SHA-256").digest(hostIdentity.encodeToByteArray())
            return Base64.getUrlEncoder().withoutPadding().encodeToString(digest).take(32)
        }
    }
}
