use std::sync::{Arc, OnceLock};

use codex_app_server::{CodexAppServer, Error as AppServerError};
use host_protocol::api;
use host_protocol::{RpcMessageKind, classify_message, raw_object, rewrite_top_level_id};
use serde_json::{Map, Value, json, value::RawValue};
use tokio::sync::broadcast;

use super::routing::{
    CodexSession, ResponseDisposition, ResponseRoute, RouteError, SessionId, SessionRouter,
};
use crate::{
    DesktopProjectStore, HOST_PROJECT_LIST_METHOD, HOST_THREAD_LIST_METHOD,
    HOST_THREAD_READ_METHOD, HOST_THREAD_START_METHOD,
};

mod history;

use history::ThreadHistory;

#[derive(Debug, thiserror::Error)]
pub enum DispatchError {
    #[error("RPC session {0} is not open")]
    UnknownSession(SessionId),
    #[error("RPC session {session} outbound queue is full")]
    QueueFull { session: SessionId },
    #[error("Codex App Server failed: {0}")]
    Upstream(#[source] Box<AppServerError>),
    #[error("invalid raw JSONL message: {0}")]
    InvalidMessage(String),
    #[error("method {method} is owned by the Host daemon")]
    DaemonOwnedMethod { method: String },
}

impl From<RouteError> for DispatchError {
    fn from(error: RouteError) -> Self {
        match error {
            RouteError::UnknownSession(session) => Self::UnknownSession(session),
            RouteError::QueueFull { session } => Self::QueueFull { session },
        }
    }
}

#[derive(Clone)]
pub struct CodexRpcService {
    inner: Arc<ServiceInner>,
}

struct ServiceInner {
    accounts: tokio::sync::Mutex<Option<crate::codex_accounts::Accounts>>,
    app_server: Arc<CodexAppServer>,
    history: ThreadHistory,
    router: SessionRouter,
    event_pump_started: OnceLock<()>,
    files: crate::workspace_files::WorkspaceFiles,
    worktrees: crate::worktrees::Worktrees,
    thread_watches: super::thread_watch::ThreadWatches,
}

impl CodexRpcService {
    pub fn new(app_server: Arc<CodexAppServer>, desktop_projects: DesktopProjectStore) -> Self {
        Self {
            inner: Arc::new(ServiceInner {
                accounts: tokio::sync::Mutex::new(None),
                history: ThreadHistory::new(app_server.clone(), desktop_projects.clone()),
                app_server,
                worktrees: crate::worktrees::Worktrees::new(desktop_projects.path()),
                router: SessionRouter::new(),
                event_pump_started: OnceLock::new(),
                files: crate::workspace_files::WorkspaceFiles::default(),
                thread_watches: super::thread_watch::ThreadWatches::default(),
            }),
        }
    }

    pub async fn enable_accounts(
        &self,
        directory: std::path::PathBuf,
        config: codex_app_server::AppServerConfig,
    ) -> Result<(), String> {
        let accounts =
            crate::codex_accounts::Accounts::load(directory, config, &self.inner.app_server)
                .await?;
        *self.inner.accounts.lock().await = Some(accounts);
        Ok(())
    }

    pub fn open_session(&self, capacity: usize) -> CodexSession {
        self.start_event_pump();
        self.inner.router.open_session(capacity)
    }

    pub fn close_session(&self, session: SessionId) {
        self.inner.thread_watches.clear_session(session);
        self.inner.files.clear_session(session);
        self.inner.router.close_session(session);
    }

    /// Begin consuming Codex-originated lines before the first phone connects.
    /// This keeps server requests replayable across phone disconnects.
    pub fn start(&self) {
        self.start_event_pump();
    }

    /// Dispatch one mobile request. The response is always queued to that
    /// session, including errors generated by the Host seam.
    pub async fn dispatch_request(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<(), DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Request {
            return Err(DispatchError::InvalidMessage(
                "request dispatcher received a non-request".to_owned(),
            ));
        }
        let method = message
            .method()
            .ok_or_else(|| DispatchError::InvalidMessage("request has no method".to_owned()))?
            .to_owned();

        if method == "turn/start" {
            let accounts = self.inner.accounts.lock().await;
            if let Some(error) = accounts
                .as_ref()
                .and_then(|accounts| accounts.restoration_error())
            {
                return self
                    .inner
                    .router
                    .send_line(
                        session,
                        error_response(&line, "account_unavailable", error)?,
                    )
                    .map_err(Into::into);
            }
        }

        let response = match method.as_str() {
            "initialize" | "initialized" => error_response(
                &line,
                "daemon_owned_method",
                &format!("{method} is managed by the Host daemon"),
            )?,
            api::ACCOUNT_LIST
            | api::ACCOUNT_SELECT
            | api::ACCOUNT_LOGIN_START
            | api::ACCOUNT_LOGIN_STATUS
            | api::ACCOUNT_LOGIN_CANCEL => {
                let mut accounts = self.inner.accounts.lock().await;
                let result = match accounts.as_mut() {
                    Some(accounts) => {
                        accounts
                            .request(&self.inner.app_server, &method, &parse_params(&line)?)
                            .await
                    }
                    None => Err("このHostはアカウント切り替えに対応していません。".into()),
                };
                match result {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "account_operation_failed", &error)?,
                }
            }
            HOST_PROJECT_LIST_METHOD => self.inner.history.host_project_list(&line).await?,
            HOST_THREAD_LIST_METHOD => {
                if parse_params(&line)?.get("titleOnly") == Some(&Value::Bool(true)) {
                    self.inner.history.host_title_list(&line).await?
                } else {
                    self.inner
                        .history
                        .host_thread_request(&line, "thread/list", false, &self.inner.worktrees)
                        .await?
                }
            }
            "host/thread/item/read" => self.inner.history.host_thread_item_read(&line).await?,
            "host/thread/watch" | "host/thread/unwatch" => {
                match self
                    .inner
                    .thread_watches
                    .request(
                        session,
                        self.inner.router.clone(),
                        method.clone(),
                        parse_params(&line)?,
                    )
                    .await
                {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "thread_watch_failed", &error)?,
                }
            }
            HOST_THREAD_READ_METHOD => {
                self.inner
                    .history
                    .host_thread_request(&line, "thread/read", true, &self.inner.worktrees)
                    .await?
            }
            "host/thread/turns/list" => {
                self.inner
                    .history
                    .host_thread_history_page(&line, false)
                    .await?
            }
            "host/thread/items/list" => {
                self.inner
                    .history
                    .host_thread_history_page(&line, true)
                    .await?
            }
            api::WORKTREE_SETTINGS_READ | api::WORKTREE_SETTINGS_UPDATE => {
                let update = if method.ends_with("/update") {
                    Some(parse_params(&line)?)
                } else {
                    None
                };
                match self.inner.worktrees.settings(update).await {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "worktree_settings_failed", &error)?,
                }
            }
            HOST_THREAD_START_METHOD | "thread/start" => {
                self.inner
                    .history
                    .host_thread_request(&line, "thread/start", false, &self.inner.worktrees)
                    .await?
            }
            "host/dictation/transcribe" => {
                match crate::dictation::transcribe(&self.inner.app_server, &parse_params(&line)?)
                    .await
                {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "dictation_failed", &error)?,
                }
            }
            api::WORKSPACE_REVIEW => {
                let params = parse_params(&line)?;
                let result = match serde_json::from_value::<api::WorkspaceReviewParams>(params) {
                    Ok(params) => crate::inspect_workspace(params.cwd.into_owned())
                        .await
                        .and_then(|result| {
                            serde_json::to_value(result).map_err(|error| error.to_string())
                        }),
                    Err(_) => Err("working directory is required".into()),
                };
                match result {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "workspace_review_failed", &error)?,
                }
            }
            api::FILE_LIST
            | api::FILE_READ
            | api::FILE_WRITE
            | "host/blob/upload"
            | "host/blob/download" => {
                match self
                    .inner
                    .files
                    .request(session, method.clone(), parse_params(&line)?)
                    .await
                {
                    Ok(result) => response_with_result(&line, result)?,
                    Err(error) => response_with_error(&line, "file_operation_failed", &error)?,
                }
            }
            _ => match self.inner.app_server.request_raw(&line).await {
                Ok(response) => response,
                Err(error) => error_response(&line, "codex_unavailable", &error.to_string())?,
            },
        };

        self.inner
            .router
            .send_line(session, response)
            .map_err(Into::into)
    }

    pub async fn dispatch_notification(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<(), DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Notification {
            return Err(DispatchError::InvalidMessage(
                "notification dispatcher received a non-notification".to_owned(),
            ));
        }
        if matches!(message.method(), Some("initialize" | "initialized")) {
            return Err(DispatchError::DaemonOwnedMethod {
                method: message.method().unwrap_or_default().to_owned(),
            });
        }
        self.inner
            .app_server
            .send_raw(&line)
            .await
            .map_err(|error| DispatchError::Upstream(Box::new(error)))
    }

    pub async fn dispatch_response(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<ResponseDisposition, DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Response {
            return Err(DispatchError::InvalidMessage(
                "response dispatcher received a non-response".to_owned(),
            ));
        }
        let Some(id) = message.raw_id() else {
            return Ok(ResponseDisposition::Unknown);
        };
        let ResponseRoute::Forward(upstream_id) = self.inner.router.resolve_response(session, id)
        else {
            return Ok(ResponseDisposition::Unknown);
        };
        let upstream_line = rewrite_top_level_id(&line, &upstream_id)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        self.inner
            .app_server
            .send_raw(&upstream_line)
            .await
            .map_err(|error| DispatchError::Upstream(Box::new(error)))?;
        Ok(ResponseDisposition::Accepted)
    }

    pub(crate) fn files(&self) -> &crate::workspace_files::WorkspaceFiles {
        &self.inner.files
    }

    fn ensure_session(&self, session: SessionId) -> Result<(), DispatchError> {
        self.inner
            .router
            .ensure_session(session)
            .map_err(Into::into)
    }

    fn start_event_pump(&self) {
        if self.inner.event_pump_started.set(()).is_err() {
            return;
        }
        // Subscribe before spawning the pump. Otherwise Codex can emit a
        // server request in the scheduling gap and it would be lost before
        // there is a receiver to retain it for the next phone.
        let mut events = self.inner.app_server.subscribe();
        let router = self.inner.router.clone();
        let thread_watches = self.inner.thread_watches.clone();
        let inner = Arc::downgrade(&self.inner);
        tokio::spawn(async move {
            loop {
                match events.recv().await {
                    Ok(line) => {
                        let request = classify_message(&line).ok();
                        if request.as_ref().is_some_and(|request| {
                            request.kind() == RpcMessageKind::Request
                                && request.method() == Some("account/chatgptAuthTokens/refresh")
                        }) {
                            let Some(inner) = inner.upgrade() else {
                                return;
                            };
                            tokio::spawn(async move {
                                let Ok(mut request) = serde_json::from_str::<Value>(&line) else {
                                    return;
                                };
                                let mut accounts = inner.accounts.lock().await;
                                let result = match accounts.as_mut() {
                                    Some(accounts) => {
                                        accounts
                                            .refresh(
                                                request["params"]["previousAccountId"].as_str(),
                                            )
                                            .await
                                    }
                                    None => Err("アカウントを選択してください。".into()),
                                };
                                let response = match result {
                                    Ok(result) => {
                                        json!({"id":request["id"].take(),"result":result})
                                    }
                                    Err(error) => {
                                        json!({"id":request["id"].take(),"error":{"code":-32000,"message":error}})
                                    }
                                };
                                let line = zeroize::Zeroizing::new(response.to_string());
                                let _ = inner.app_server.send_raw(&line).await;
                            });
                        } else {
                            router.handle_server_line(&line);
                        }
                    }
                    Err(broadcast::error::RecvError::Closed)
                    | Err(broadcast::error::RecvError::Lagged(_)) => {
                        thread_watches.clear_all();
                        router.close_all();
                        return;
                    }
                }
            }
        });
    }
}

fn parse_params(line: &str) -> Result<Value, DispatchError> {
    let object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let Some(params) = object.get("params") else {
        return Ok(Value::Object(Map::new()));
    };
    serde_json::from_str(params.get())
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn replace_method(line: &str, method: &str) -> Result<String, DispatchError> {
    let mut object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let method = serde_json::to_string(method)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let method: Box<RawValue> = serde_json::from_str(&method)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    object.insert("method".to_owned(), method);
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_with_result(line: &str, result: Value) -> Result<String, DispatchError> {
    let mut object = response_object(line)?;
    object.insert("result".to_owned(), raw_value(result)?);
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_with_error(
    line: &str,
    code: &str,
    detail: &dyn std::fmt::Display,
) -> Result<String, DispatchError> {
    error_response(line, code, &detail.to_string())
}

fn error_response(line: &str, code: &str, message: &str) -> Result<String, DispatchError> {
    let mut object = response_object(line)?;
    object.insert(
        "error".to_owned(),
        raw_value(json!(api::HostError { code, message }))?,
    );
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_object(
    line: &str,
) -> Result<std::collections::BTreeMap<String, Box<RawValue>>, DispatchError> {
    let mut object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    object.remove("method");
    object.remove("params");
    object.remove("result");
    object.remove("error");
    Ok(object)
}

fn raw_value(value: Value) -> Result<Box<RawValue>, DispatchError> {
    serde_json::value::to_raw_value(&value)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn host_response_keeps_request_extensions_and_raw_id() {
        let line = r#"{"jsonrpc":"2.0","id":"mobile-1","method":"host/project/list","params":{"future":{"id":9}},"extension":{"keep":[1,true]}}"#;
        let response = response_with_result(line, json!({"data":[]})).unwrap();
        let object = raw_object(&response).unwrap();
        assert_eq!(object["id"].get(), r#""mobile-1""#);
        assert_eq!(object["extension"].get(), r#"{"keep":[1,true]}"#);
        assert_eq!(object["result"].get(), r#"{"data":[]}"#);
        assert!(!object.contains_key("params"));
        assert!(!object.contains_key("method"));
    }
}
