use std::sync::{Arc, OnceLock};

use codex_app_server::{CodexAppServer, Error as AppServerError};
use host_protocol::{RpcMessageKind, classify_message, raw_object, rewrite_top_level_id};
use serde_json::{Map, Value, json, value::RawValue};
use tokio::sync::broadcast;

use super::routing::{
    CodexSession, ResponseDisposition, ResponseRoute, RouteError, SessionId, SessionRouter,
};
use crate::{
    DesktopProjectStore, HOST_PROJECT_LIST_METHOD, HOST_THREAD_LIST_METHOD,
    HOST_THREAD_READ_METHOD, HOST_THREAD_START_METHOD,
};

const MAX_MOBILE_THREAD_TURNS: usize = 10;

#[derive(Debug, thiserror::Error)]
pub enum DispatchError {
    #[error("RPC session {0} is not open")]
    UnknownSession(SessionId),
    #[error("RPC session {session} outbound queue is full")]
    QueueFull { session: SessionId },
    #[error("Codex App Server failed: {0}")]
    Upstream(#[source] Box<AppServerError>),
    #[error("invalid raw JSONL message: {0}")]
    InvalidMessage(String),
    #[error("message has no top-level id")]
    MissingId,
    #[error("method {method} is owned by the Host daemon")]
    DaemonOwnedMethod { method: String },
}

impl From<RouteError> for DispatchError {
    fn from(error: RouteError) -> Self {
        match error {
            RouteError::UnknownSession(session) => Self::UnknownSession(session),
            RouteError::QueueFull { session } => Self::QueueFull { session },
        }
    }
}

#[derive(Clone)]
pub struct CodexRpcService {
    inner: Arc<ServiceInner>,
}

struct ServiceInner {
    app_server: Arc<CodexAppServer>,
    desktop_projects: DesktopProjectStore,
    router: SessionRouter,
    event_pump_started: OnceLock<()>,
}

impl CodexRpcService {
    pub fn new(app_server: Arc<CodexAppServer>, desktop_projects: DesktopProjectStore) -> Self {
        Self {
            inner: Arc::new(ServiceInner {
                app_server,
                desktop_projects,
                router: SessionRouter::new(),
                event_pump_started: OnceLock::new(),
            }),
        }
    }

    pub fn open_session(&self, capacity: usize) -> CodexSession {
        self.start_event_pump();
        self.inner.router.open_session(capacity)
    }

    pub fn close_session(&self, session: SessionId) {
        self.inner.router.close_session(session);
    }

    /// Begin consuming Codex-originated lines before the first phone connects.
    /// This keeps server requests replayable across phone disconnects.
    pub fn start(&self) {
        self.start_event_pump();
    }

    /// Dispatch one mobile request. The response is always queued to that
    /// session, including errors generated by the Host seam.
    pub async fn dispatch_request(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<(), DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Request {
            return Err(DispatchError::InvalidMessage(
                "request dispatcher received a non-request".to_owned(),
            ));
        }
        let method = message
            .method()
            .ok_or_else(|| DispatchError::InvalidMessage("request has no method".to_owned()))?
            .to_owned();

        let response = match method.as_str() {
            "initialize" | "initialized" => error_response(
                &line,
                "daemon_owned_method",
                &format!("{method} is managed by the Host daemon"),
            )?,
            HOST_PROJECT_LIST_METHOD => self.host_project_list(&line).await?,
            HOST_THREAD_LIST_METHOD => {
                self.host_thread_request(&line, "thread/list", false)
                    .await?
            }
            HOST_THREAD_READ_METHOD => self.host_thread_request(&line, "thread/read", true).await?,
            HOST_THREAD_START_METHOD => {
                self.host_thread_request(&line, "thread/start", false)
                    .await?
            }
            _ => match self.inner.app_server.request_raw(&line).await {
                Ok(response) => response,
                Err(error) => error_response(&line, "codex_unavailable", &error.to_string())?,
            },
        };

        self.inner
            .router
            .send_line(session, response)
            .map_err(Into::into)
    }

    pub async fn dispatch_notification(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<(), DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Notification {
            return Err(DispatchError::InvalidMessage(
                "notification dispatcher received a non-notification".to_owned(),
            ));
        }
        if matches!(message.method(), Some("initialize" | "initialized")) {
            return Err(DispatchError::DaemonOwnedMethod {
                method: message.method().unwrap_or_default().to_owned(),
            });
        }
        self.inner
            .app_server
            .notify_raw(&line)
            .await
            .map_err(|error| DispatchError::Upstream(Box::new(error)))
    }

    pub async fn dispatch_response(
        &self,
        session: SessionId,
        line: String,
    ) -> Result<ResponseDisposition, DispatchError> {
        self.ensure_session(session)?;
        let message = classify_message(&line)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        if message.kind() != RpcMessageKind::Response {
            return Err(DispatchError::InvalidMessage(
                "response dispatcher received a non-response".to_owned(),
            ));
        }
        let Some(id) = message.raw_id() else {
            return Ok(ResponseDisposition::Unknown);
        };
        let ResponseRoute::Forward(upstream_id) = self.inner.router.resolve_response(session, id)
        else {
            return Ok(ResponseDisposition::Unknown);
        };
        let upstream_line = rewrite_top_level_id(&line, &upstream_id)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        self.inner
            .app_server
            .respond_raw(&upstream_line)
            .await
            .map_err(|error| DispatchError::Upstream(Box::new(error)))?;
        Ok(ResponseDisposition::Accepted)
    }

    fn ensure_session(&self, session: SessionId) -> Result<(), DispatchError> {
        self.inner
            .router
            .ensure_session(session)
            .map_err(Into::into)
    }

    async fn host_project_list(&self, line: &str) -> Result<String, DispatchError> {
        let params = parse_params(line)?;
        match self.inner.desktop_projects.project_list(&params).await {
            Ok(result) => response_with_result(line, result),
            Err(error) => response_with_error(line, "desktop_project_state_unavailable", &error),
        }
    }

    async fn host_thread_request(
        &self,
        line: &str,
        upstream_method: &str,
        retain_recent_turns: bool,
    ) -> Result<String, DispatchError> {
        let upstream_line = replace_method(line, upstream_method)?;
        let response = match self.inner.app_server.request_raw(&upstream_line).await {
            Ok(response) => response,
            Err(error) => return response_with_error(line, "codex_unavailable", &error),
        };
        let object = raw_object(&response)
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        let Some(raw_result) = object.get("result") else {
            // Error responses and future response shapes remain untouched.
            return Ok(response);
        };
        let result: Value = serde_json::from_str(raw_result.get())
            .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
        let result = match self.inner.desktop_projects.enrich_threads(result).await {
            Ok(result) => result,
            Err(error) => {
                return response_with_error(line, "desktop_project_state_unavailable", &error);
            }
        };
        let result = if retain_recent_turns {
            retain_recent_thread_turns(result, MAX_MOBILE_THREAD_TURNS)
        } else {
            result
        };
        replace_result(&response, result)
    }

    fn start_event_pump(&self) {
        if self.inner.event_pump_started.set(()).is_err() {
            return;
        }
        // Subscribe before spawning the pump. Otherwise Codex can emit a
        // server request in the scheduling gap and it would be lost before
        // there is a receiver to retain it for the next phone.
        let mut events = self.inner.app_server.subscribe();
        let router = self.inner.router.clone();
        tokio::spawn(async move {
            loop {
                match events.recv().await {
                    Ok(line) => router.handle_server_line(&line),
                    Err(broadcast::error::RecvError::Closed)
                    | Err(broadcast::error::RecvError::Lagged(_)) => {
                        router.close_all();
                        return;
                    }
                }
            }
        });
    }
}

fn parse_params(line: &str) -> Result<Value, DispatchError> {
    let object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let Some(params) = object.get("params") else {
        return Ok(Value::Object(Map::new()));
    };
    serde_json::from_str(params.get())
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn replace_method(line: &str, method: &str) -> Result<String, DispatchError> {
    let mut object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let method = serde_json::to_string(method)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    let method: Box<RawValue> = serde_json::from_str(&method)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    object.insert("method".to_owned(), method);
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_with_result(line: &str, result: Value) -> Result<String, DispatchError> {
    let mut object = response_object(line)?;
    object.insert("result".to_owned(), raw_value(result)?);
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_with_error(
    line: &str,
    code: &str,
    detail: &dyn std::fmt::Display,
) -> Result<String, DispatchError> {
    error_response(line, code, &detail.to_string())
}

fn error_response(line: &str, code: &str, message: &str) -> Result<String, DispatchError> {
    let mut object = response_object(line)?;
    object.insert(
        "error".to_owned(),
        raw_value(json!({"code": code, "message": message}))?,
    );
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn response_object(
    line: &str,
) -> Result<std::collections::BTreeMap<String, Box<RawValue>>, DispatchError> {
    let mut object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    object.remove("method");
    object.remove("params");
    object.remove("result");
    object.remove("error");
    Ok(object)
}

fn replace_result(line: &str, result: Value) -> Result<String, DispatchError> {
    let mut object =
        raw_object(line).map_err(|error| DispatchError::InvalidMessage(error.to_string()))?;
    object.insert("result".to_owned(), raw_value(result)?);
    serde_json::to_string(&object).map_err(|error| DispatchError::InvalidMessage(error.to_string()))
}

fn raw_value(value: Value) -> Result<Box<RawValue>, DispatchError> {
    serde_json::to_string(&value)
        .map_err(|error| DispatchError::InvalidMessage(error.to_string()))
        .and_then(|value| {
            serde_json::from_str(&value)
                .map_err(|error| DispatchError::InvalidMessage(error.to_string()))
        })
}

fn retain_recent_thread_turns(mut result: Value, maximum: usize) -> Value {
    if let Some(turns) = result
        .get_mut("thread")
        .and_then(Value::as_object_mut)
        .and_then(|thread| thread.get_mut("turns"))
        .and_then(Value::as_array_mut)
    {
        let retained_from = turns.len().saturating_sub(maximum);
        if retained_from > 0 {
            *turns = turns.split_off(retained_from);
        }
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn host_response_keeps_request_extensions_and_raw_id() {
        let line = r#"{"jsonrpc":"2.0","id":"mobile-1","method":"host/project/list","params":{"future":{"id":9}},"extension":{"keep":[1,true]}}"#;
        let response = response_with_result(line, json!({"data":[]})).unwrap();
        let object = raw_object(&response).unwrap();
        assert_eq!(object["id"].get(), r#""mobile-1""#);
        assert_eq!(object["extension"].get(), r#"{"keep":[1,true]}"#);
        assert_eq!(object["result"].get(), r#"{"data":[]}"#);
        assert!(!object.contains_key("params"));
        assert!(!object.contains_key("method"));
    }

    #[test]
    fn latest_ten_turns_are_retained() {
        let turns = (1..=12)
            .map(|id| json!({"id": format!("turn-{id}")}))
            .collect::<Vec<_>>();
        let result = retain_recent_thread_turns(json!({"thread":{"turns":turns}}), 10);
        assert_eq!(result["thread"]["turns"].as_array().unwrap().len(), 10);
        assert_eq!(result["thread"]["turns"][0]["id"], "turn-3");
    }
}
